#!/usr/bin/env node
// Regenerates src/dashboard/vendor.ts from pinned htmx + Alpine releases.
// Run manually when bumping versions; the output is checked in so the
// build has no network dependency.
import { atomicWritePrivate, boundedResponseText, sha256Text } from '../eval/lib/io-safety.mjs';

const PINS = [
  ['HTMX_JS', 'https://unpkg.com/htmx.org@2.0.4/dist/htmx.min.js', 'e209dda5c8235479f3166defc7750e1dbcd5a5c1808b7792fc2e6733768fb447'],
  ['ALPINE_JS', 'https://unpkg.com/alpinejs@3.14.9/dist/cdn.min.js', '3ed1eed252488921df65e363d6715deb04d7f92aaedb9e52199fdf73cb1e0ad3'],
];

let out =
  '// GENERATED by scripts/vendor-ui.mjs - do not edit by hand.\n' +
  '// htmx 2.0.4 (BSD-2) + Alpine.js 3.14.9 (MIT), inlined so the dashboard\n' +
  '// works offline and ships inside the single-file npm package.\n';
for (const [name, url, expectedSha256] of PINS) {
  const parsed = new URL(url);
  if (parsed.protocol !== 'https:' || parsed.hostname !== 'unpkg.com' || parsed.username || parsed.password || parsed.search || parsed.hash) throw new Error(`unsafe vendor URL: ${url}`);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: ${res.status}`);
  const js = await boundedResponseText(res, 128 * 1024);
  if (sha256Text(js) !== expectedSha256) throw new Error(`${url}: SHA-256 mismatch`);
  out += `\nexport const ${name} = ${JSON.stringify(js)};\n`;
}
atomicWritePrivate('src/dashboard/vendor.ts', out);
console.log('wrote src/dashboard/vendor.ts');
